runtime: python
env: flex
entrypoint: python predict.py

runtime_config:
  python_version: 3

# [START configuration]
endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy openapi-appengine.yaml' command.
  name: ml-api-unbiased.appspot.com
  rollout_strategy: managed
 # [END configuration]